name: Deploy to Hugging Face Space

on:
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/tgao09/marketAnalysis hf-space
          rsync -av --delete --exclude='.git' ./ hf-space/
          cd hf-space
          git add ./greenfield/arimax/
          git commit -m "Sync from GitHub repo" || echo "No changes to commit"
          git push https://user:$HF_TOKEN@huggingface.co/spaces/<USERNAME>/<SPACE_NAME> main
